version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
      - .env-dev-values

  database:
    build: lib/dev_db/.

  falma:
    build: ./fake_alma/.
    ports:
      - "4444:4567"
    volumes:
      - ./fake_alma/.:/app
  
volumes:
  gem_cache:
  db_data:
