version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env/web
      - .env/database
        
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env/database
    volumes:
      - db_data:/var/lib/mysql
        #command: --default-authentication-plugin=mysql_native_password

volumes:
  gem_cache:
  db_data:
