version: '3'

services:
  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - CIRC_REPORT_PATH=/circ/report/path
      - PATRON_REPORT_PATH=/patron/report/path
      - ALMA_API_KEY=YOUR_ALMA_API_KEY
      - ALMA_API_HOST=http://falma:4567
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - DATABASE_HOST=database


  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - DATABASE_HOST=database

volumes:
  gem_cache:
