version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - CIRCULATION_HISTORY_DATABASE_PASSWORD=circulation_history_db_password
      - DATABASE_HOST=database
      - CIRC_REPORT_PATH=/circ/report/path
      - PATRON_REPORT_PATH=/patron/report/path
      - ALMA_API_HOST=http://falma:4567
      - RAILS_LOG_TO_STDOUT=1
        #- RAILS_ENV=production
    env_file:
      - .env

  database:
    build: lib/dev_db/.

  falma:
    build: ./fake_alma/.
    ports:
      - "4444:4567"
    volumes:
      - ./fake_alma/.:/app

  
  #promtail:
    #image: grafana/promtail
    #ports:
      #- "9080:9080"
    #volumes: 
      #- ./log/development.log:/development.log
      #- ./config/promtail.yml:/promtail.yml
    #command: -config.file=/promtail.yml
    
  #grafana:
    #image: grafana/grafana:7.1.1
    #ports:
      #- "3000:3000"
    #volumes:
      #- ./.env/grafana.ini:/etc/grafana/grafana.ini
      #- grafana_storage:/var/lib/grafana
  
  #loki:
    #image: grafana/loki:master
    #ports:
      #- "3100:3100"
    #command: -config.file=/etc/loki/local-config.yaml
    
  #prometheus:
    #image: prom/prometheus
    #ports: 
      #- "9090:9090"
    #volumes:
      #- ./config/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  gem_cache:
  db_data:
#  grafana_storage:
