version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
      - .env-dev-values

  database:
    build: lib/dev_db/.

  falma:
    build: ./fake_alma/.
    ports:
      - "4444:4567"
    volumes:
      - ./fake_alma/.:/app

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  
volumes:
  gem_cache:
  db_data:
