name: Build latest from main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        image_name: unstable
        tags: |
          latest
          ${{ github.sha }}
    - uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        context: db/development_db/.
        image_name: dev-db
        tags: |
          latest
          ${{ github.sha }}
