name: Run Tests

on: 
  push:
    branches: [ main ]

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache ruby gems
        uses: actions/cache@v2
        env:
          cache-name: ruby-gems
        with:
          path: .gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: make coverage directory
        run: mkdir -m777 coverage 
      - name: make tmp directory writeable
        run: chmod -R 777 tmp
      - name: make fixtures writeable
        run: chmod -R 777 spec/fixtures
      - name: make app/log/development.log writeable
        run: |
          mkdir -m777 log
          touch log/development.log
          chmod 777 log/development.log
      - name: list files with permissions
        run: |
          ls -al
          ls -al log
      - name: Set up tests
        run: |
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml run web bundle install
      - name: boot up database
        run: docker-compose -f docker-compose.test.yml up -d database
      - name: docker state
        run: docker-compose -f docker-compose.test.yml ps
      - name: create databases
        run: docker-compose -f docker-compose.test.yml run web bundle exec rails db:create

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run web bundle exec rspec


