name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10
        env:
          MARIADB_USER: circulation_history
          MARIADB_PASSWORD: circulation_history_db_password
          MARIADB_DATABASE: circulation_history_test
          MARIADB_ROOT_PASSWORD: pass
        ports: ["3306:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          sed 's/DATABASE_HOST=database/DATABASE_HOST=127.0.0.1/' .env-dev-values > .env-actions
          cat .env-example .env-actions > .env

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Setup up node 16.14.2
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Verify MariaDB connection
        run: | 
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done   
      - name: Set up DB
        run: bundle exec rails db:schema:load RAILS_ENV=test
      - name: Run tests
        run: bundle exec rspec
